/**
 * Generated from the user-provided Qwen intake attachment.
 * The original cited DOCX/reference was not supplied, so every entry is shown as a review intake—not a verified legal or contractual authority.
 * Source is archived locally in docs/sources/qwen-case-intake-d056-d088.json; rerun pnpm content:qwen-intake to refresh.
 */

import type { MasterClaimIntelligenceCase } from "./master-claim-intelligence-data";

export const qwenCaseIntakeSource = {
  "filename": "qwen-case-intake-d056-d088.json",
  "userConfirmedPurpose": "Complete the library with Qwen-supplied cases",
  "reviewStatus": "user-provided intake; original cited source not independently verified",
  "originalSourceAvailable": false,
  "caseCount": 33,
  "caseIds": [
    "D-056",
    "D-057",
    "D-058",
    "D-059",
    "D-060",
    "D-061",
    "D-062",
    "D-063",
    "D-064",
    "D-065",
    "D-066",
    "D-067",
    "D-068",
    "D-069",
    "D-070",
    "D-071",
    "D-072",
    "D-073",
    "D-074",
    "D-075",
    "D-076",
    "D-077",
    "D-078",
    "D-079",
    "D-080",
    "D-081",
    "D-082",
    "D-083",
    "D-084",
    "D-085",
    "D-086",
    "D-087",
    "D-088"
  ]
} as const;

export const qwenCaseIntakeCases: MasterClaimIntelligenceCase[] = [
  {
    "id": "D-056",
    "case_id": "D-056",
    "title_ar": "تأخر توفير الرسومات التنفيذية IFC/As-Built",
    "title_en": "Late Issue of IFC / As-Built Drawings",
    "category": "Owner/Consultant Delay",
    "delay_type": "T + C",
    "methodology": "TIA",
    "description": "متوسط 50 يوم في المشاريع المصرية",
    "root_cause": "Not independently verified; review the original cited material and project facts.",
    "schedule_impact": "Fragnet cue as recorded: FR-056_A Late Issue of IFC → FR-056_B Revision Cycle → FR-056_C Resume Works",
    "recommended_solution": "Use this as an intake cue only; define the event, affected activities and links against the actual update before analysis.",
    "mitigation": "Not provided in the supplied intake.",
    "contractual_basis": "Source reference / مرجع المصدر: 1.9\n\nLegal locator as recorded / مؤشر قانوني كما ورد: مدني 147، 215\n\nSource locator as recorded / مؤشر المصدر كما ورد: ف1/ح11",
    "fragnet_id": "FR-056_A Late Issue of IFC → FR-056_B Revision Cycle → FR-056_C Resume Works",
    "wbs_code": "",
    "fragnet_activities": "",
    "fragnet_protocol": "FR-056_A Late Issue of IFC → FR-056_B Revision Cycle → FR-056_C Resume Works",
    "tia_baseline_rule": "Verify the applicable baseline/update and data date against the project record.",
    "calendar_rule": "Verify the project calendar before calculating any impact.",
    "float_rule": "Verify total-float treatment against the contract and accepted programme.",
    "burden_of_proof": "Evidence requirements were not listed in the supplied intake.",
    "update_procedure": "F3 نشاط 'Late Issue of IFC Drawings'\n\nDuration=أيام التأخير\n\nFS لأول نشاط تنفيذ معتمد عليها\n\nF9 وقارن الـ Float/تاريخ الانتهاء",
    "recovery_procedure": "Not provided in the supplied intake."
  },
  {
    "id": "D-057",
    "case_id": "D-057",
    "title_ar": "تأخر إصدار تعليمات الموقع",
    "title_en": "Delayed Site Instructions",
    "category": "Owner/Consultant Delay",
    "delay_type": "T + C",
    "methodology": "TIA",
    "description": "مستشفى 6 أكتوبر (2024) – 52 يوم",
    "root_cause": "Not independently verified; review the original cited material and project facts.",
    "schedule_impact": "Fragnet cue as recorded: FR-057_A Awaiting Site Instruction → FR-057_B Instruction Issued → FR-057_C Resume",
    "recommended_solution": "Use this as an intake cue only; define the event, affected activities and links against the actual update before analysis.",
    "mitigation": "Not provided in the supplied intake.",
    "contractual_basis": "Source reference / مرجع المصدر: 3.3 / 1.9\n\nLegal locator as recorded / مؤشر قانوني كما ورد: مدني 147\n\nSource locator as recorded / مؤشر المصدر كما ورد: ف1/ح5",
    "fragnet_id": "FR-057_A Awaiting Site Instruction → FR-057_B Instruction Issued → FR-057_C Resume",
    "wbs_code": "",
    "fragnet_activities": "",
    "fragnet_protocol": "FR-057_A Awaiting Site Instruction → FR-057_B Instruction Issued → FR-057_C Resume",
    "tia_baseline_rule": "Verify the applicable baseline/update and data date against the project record.",
    "calendar_rule": "Verify the project calendar before calculating any impact.",
    "float_rule": "Verify total-float treatment against the contract and accepted programme.",
    "burden_of_proof": "Evidence requirements were not listed in the supplied intake.",
    "update_procedure": "F3 'Awaiting Site Instruction for MEP'\n\nDuration=التأخير\n\nFS بالأنشطة المتوقفة\n\nF9",
    "recovery_procedure": "Not provided in the supplied intake."
  },
  {
    "id": "D-058",
    "case_id": "D-058",
    "title_ar": "تأخر إصدار/اعتماد أوامر التغيير",
    "title_en": "Pending Variation Order Approval",
    "category": "Design Changes & VO",
    "delay_type": "T + C",
    "methodology": "TIA",
    "description": "برج بالتجمع (2022) – 60 يوم + تعويض",
    "root_cause": "Not independently verified; review the original cited material and project facts.",
    "schedule_impact": "Fragnet cue as recorded: FR-058_A VO Submitted → FR-058_B Pending Approval → FR-058_C Execute New Works",
    "recommended_solution": "Use this as an intake cue only; define the event, affected activities and links against the actual update before analysis.",
    "mitigation": "Not provided in the supplied intake.",
    "contractual_basis": "Source reference / مرجع المصدر: 13.3\n\nLegal locator as recorded / مؤشر قانوني كما ورد: مدني 147\n\nSource locator as recorded / مؤشر المصدر كما ورد: ف1/ح6",
    "fragnet_id": "FR-058_A VO Submitted → FR-058_B Pending Approval → FR-058_C Execute New Works",
    "wbs_code": "",
    "fragnet_activities": "",
    "fragnet_protocol": "FR-058_A VO Submitted → FR-058_B Pending Approval → FR-058_C Execute New Works",
    "tia_baseline_rule": "Verify the applicable baseline/update and data date against the project record.",
    "calendar_rule": "Verify the project calendar before calculating any impact.",
    "float_rule": "Verify total-float treatment against the contract and accepted programme.",
    "burden_of_proof": "Evidence requirements were not listed in the supplied intake.",
    "update_procedure": "F3 'Pending VO-27 Approval'\n\nDuration=التأخير\n\nFS بالأعمال الجديدة\n\nF9",
    "recovery_procedure": "Not provided in the supplied intake."
  },
  {
    "id": "D-059",
    "case_id": "D-059",
    "title_ar": "تأخر ترشيح/توريد مقاول Nominated",
    "title_en": "Nominated Subcontractor Delay",
    "category": "Owner/Consultant Delay",
    "delay_type": "T + C",
    "methodology": "TIA",
    "description": "أبراج العلمين (2023) – EOT 90 يوم؛ برج العرب 70 يوم",
    "root_cause": "Not independently verified; review the original cited material and project facts.",
    "schedule_impact": "Fragnet cue as recorded: WBS: Nominated Subs | FR-059_A Nomination → FR-059_B Nominated Delay → FR-059_C Installation",
    "recommended_solution": "Use this as an intake cue only; define the event, affected activities and links against the actual update before analysis.",
    "mitigation": "Not provided in the supplied intake.",
    "contractual_basis": "Source reference / مرجع المصدر: 5.2\n\nLegal locator as recorded / مؤشر قانوني كما ورد: مدني 215، 650\n\nSource locator as recorded / مؤشر المصدر كما ورد: ف1/ح7",
    "fragnet_id": "WBS: Nominated Subs | FR-059_A Nomination → FR-059_B Nominated Delay → FR-059_C Installation",
    "wbs_code": "",
    "fragnet_activities": "",
    "fragnet_protocol": "WBS: Nominated Subs | FR-059_A Nomination → FR-059_B Nominated Delay → FR-059_C Installation",
    "tia_baseline_rule": "Verify the applicable baseline/update and data date against the project record.",
    "calendar_rule": "Verify the project calendar before calculating any impact.",
    "float_rule": "Verify total-float treatment against the contract and accepted programme.",
    "burden_of_proof": "Evidence requirements were not listed in the supplied intake.",
    "update_procedure": "WBS فرعي Nominated\n\nF3 'Delay by Nominated Lift Contractor'\n\nFS بتركيب المصاعد\n\nF9",
    "recovery_procedure": "Not provided in the supplied intake."
  },
  {
    "id": "D-060",
    "case_id": "D-060",
    "title_ar": "تأخر الموافقات الأمنية",
    "title_en": "Security Clearance Delay",
    "category": "Permits & Authorities (EG)",
    "delay_type": "T",
    "methodology": "TIA",
    "description": "مشاريع العاصمة (2024) – 75 يوم",
    "root_cause": "Not independently verified; review the original cited material and project facts.",
    "schedule_impact": "Fragnet cue as recorded: FR-060_A Application → FR-060_B Security Review → FR-060_C Clearance Issued",
    "recommended_solution": "Use this as an intake cue only; define the event, affected activities and links against the actual update before analysis.",
    "mitigation": "Not provided in the supplied intake.",
    "contractual_basis": "Source reference / مرجع المصدر: 8.5\n\nLegal locator as recorded / مؤشر قانوني كما ورد: مدني 165، 148\n\nSource locator as recorded / مؤشر المصدر كما ورد: ف1/ح8",
    "fragnet_id": "FR-060_A Application → FR-060_B Security Review → FR-060_C Clearance Issued",
    "wbs_code": "",
    "fragnet_activities": "",
    "fragnet_protocol": "FR-060_A Application → FR-060_B Security Review → FR-060_C Clearance Issued",
    "tia_baseline_rule": "Verify the applicable baseline/update and data date against the project record.",
    "calendar_rule": "Verify the project calendar before calculating any impact.",
    "float_rule": "Verify total-float treatment against the contract and accepted programme.",
    "burden_of_proof": "Evidence requirements were not listed in the supplied intake.",
    "update_procedure": "F3 'Security Clearance Delay – Army'\n\nDuration=التأخير\n\nFS بالأعمال الحساسة\n\nF9",
    "recovery_procedure": "Not provided in the supplied intake."
  },
  {
    "id": "D-061",
    "case_id": "D-061",
    "title_ar": "تأخر توفير كهرباء/مياه مؤقتة للموقع",
    "title_en": "Temporary Utilities Delay",
    "category": "Owner/Consultant Delay",
    "delay_type": "T + C",
    "methodology": "TIA",
    "description": "الشيخ زايد (2022) – 40 يوم",
    "root_cause": "Not independently verified; review the original cited material and project facts.",
    "schedule_impact": "Fragnet cue as recorded: FR-061_A Request → FR-061_B Utility Delay → FR-061_C Energize Site",
    "recommended_solution": "Use this as an intake cue only; define the event, affected activities and links against the actual update before analysis.",
    "mitigation": "Not provided in the supplied intake.",
    "contractual_basis": "Source reference / مرجع المصدر: 4.19\n\nLegal locator as recorded / مؤشر قانوني كما ورد: مدني 148\n\nSource locator as recorded / مؤشر المصدر كما ورد: ف1/ح10",
    "fragnet_id": "FR-061_A Request → FR-061_B Utility Delay → FR-061_C Energize Site",
    "wbs_code": "",
    "fragnet_activities": "",
    "fragnet_protocol": "FR-061_A Request → FR-061_B Utility Delay → FR-061_C Energize Site",
    "tia_baseline_rule": "Verify the applicable baseline/update and data date against the project record.",
    "calendar_rule": "Verify the project calendar before calculating any impact.",
    "float_rule": "Verify total-float treatment against the contract and accepted programme.",
    "burden_of_proof": "Evidence requirements were not listed in the supplied intake.",
    "update_procedure": "F3 'Temporary Utilities Delay'\n\nDuration=التوقف\n\nFS بالأعمال المحتاجة طاقة\n\nF9",
    "recovery_procedure": "Not provided in the supplied intake."
  },
  {
    "id": "D-062",
    "case_id": "D-062",
    "title_ar": "تدخل المالك في اختيار الموردين/المواد",
    "title_en": "Owner Interference in Suppliers",
    "category": "Owner/Consultant Delay",
    "delay_type": "T + C",
    "methodology": "TIA",
    "description": "مشروع بالرياض (2024) – 35 يوم",
    "root_cause": "Not independently verified; review the original cited material and project facts.",
    "schedule_impact": "Fragnet cue as recorded: FR-062_A Interference Instruction → FR-062_B Re-Procurement → FR-062_C Delivery",
    "recommended_solution": "Use this as an intake cue only; define the event, affected activities and links against the actual update before analysis.",
    "mitigation": "Not provided in the supplied intake.",
    "contractual_basis": "Source reference / مرجع المصدر: 4.1 / 13.1\n\nLegal locator as recorded / مؤشر قانوني كما ورد: مدني 147\n\nSource locator as recorded / مؤشر المصدر كما ورد: ف1/ح12",
    "fragnet_id": "FR-062_A Interference Instruction → FR-062_B Re-Procurement → FR-062_C Delivery",
    "wbs_code": "",
    "fragnet_activities": "",
    "fragnet_protocol": "FR-062_A Interference Instruction → FR-062_B Re-Procurement → FR-062_C Delivery",
    "tia_baseline_rule": "Verify the applicable baseline/update and data date against the project record.",
    "calendar_rule": "Verify the project calendar before calculating any impact.",
    "float_rule": "Verify total-float treatment against the contract and accepted programme.",
    "burden_of_proof": "Evidence requirements were not listed in the supplied intake.",
    "update_procedure": "F3 'Owner Interference in Suppliers'\n\nDuration=التأخير\n\nFS بالتوريد\n\nF9",
    "recovery_procedure": "Not provided in the supplied intake."
  },
  {
    "id": "D-063",
    "case_id": "D-063",
    "title_ar": "أمر إزالة أعمال منفذة سليمة",
    "title_en": "Instruction to Remove Completed Sound Works",
    "category": "Design Changes & VO",
    "delay_type": "T + C",
    "methodology": "TIA",
    "description": "فندق شرم الشيخ (2022) – تعويض 20 مليون",
    "root_cause": "Not independently verified; review the original cited material and project facts.",
    "schedule_impact": "Fragnet cue as recorded: FR-063_A Removal Instruction → FR-063_B Demolish → FR-063_C Re-Execute",
    "recommended_solution": "Use this as an intake cue only; define the event, affected activities and links against the actual update before analysis.",
    "mitigation": "Not provided in the supplied intake.",
    "contractual_basis": "Source reference / مرجع المصدر: 13.1\n\nLegal locator as recorded / مؤشر قانوني كما ورد: مدني 651\n\nSource locator as recorded / مؤشر المصدر كما ورد: ف1/ح14",
    "fragnet_id": "FR-063_A Removal Instruction → FR-063_B Demolish → FR-063_C Re-Execute",
    "wbs_code": "",
    "fragnet_activities": "",
    "fragnet_protocol": "FR-063_A Removal Instruction → FR-063_B Demolish → FR-063_C Re-Execute",
    "tia_baseline_rule": "Verify the applicable baseline/update and data date against the project record.",
    "calendar_rule": "Verify the project calendar before calculating any impact.",
    "float_rule": "Verify total-float treatment against the contract and accepted programme.",
    "burden_of_proof": "Evidence requirements were not listed in the supplied intake.",
    "update_procedure": "F3 'Instruction to Remove Completed Works'\n\nDuration=الإزالة+الإعادة\n\nFS بالأعمال الجديدة\n\nF9",
    "recovery_procedure": "Not provided in the supplied intake."
  },
  {
    "id": "D-064",
    "case_id": "D-064",
    "title_ar": "رفض EOT ظلماً → Constructive Acceleration",
    "title_en": "Constructive Acceleration",
    "category": "Owner/Consultant Delay",
    "delay_type": "C",
    "methodology": "مقارنة برنامجين + MM (بدون Fragnet للزمن)",
    "description": "مستشفى 57357 (2022) – 47 مليون Acceleration",
    "root_cause": "Not independently verified; review the original cited material and project facts.",
    "schedule_impact": "Fragnet cue as recorded: N/A — برنامج أصلي بدون EOT مقابل برنامج ورديات إضافية",
    "recommended_solution": "Use this as an intake cue only; define the event, affected activities and links against the actual update before analysis.",
    "mitigation": "Not provided in the supplied intake.",
    "contractual_basis": "Source reference / مرجع المصدر: 8.4 + 20.1\n\nLegal locator as recorded / مؤشر قانوني كما ورد: مدني 159\n\nSource locator as recorded / مؤشر المصدر كما ورد: ف1/ح16",
    "fragnet_id": "N/A — برنامج أصلي بدون EOT مقابل برنامج ورديات إضافية",
    "wbs_code": "",
    "fragnet_activities": "",
    "fragnet_protocol": "N/A — برنامج أصلي بدون EOT مقابل برنامج ورديات إضافية",
    "tia_baseline_rule": "Verify the applicable baseline/update and data date against the project record.",
    "calendar_rule": "Verify the project calendar before calculating any impact.",
    "float_rule": "Verify total-float treatment against the contract and accepted programme.",
    "burden_of_proof": "Evidence requirements were not listed in the supplied intake.",
    "update_procedure": "احتفظ بالبرنامج الأصلي\n\nابنِ نسخة بورديات إضافية\n\nF9 للنسختين وقارن التكلفة",
    "recovery_procedure": "Not provided in the supplied intake."
  },
  {
    "id": "D-065",
    "case_id": "D-065",
    "title_ar": "إلغاء أعمال كبيرة بعد التنفيذ مع إعادة إسناد",
    "title_en": "Omission of Works with Re-assignment",
    "category": "Design Changes & VO",
    "delay_type": "C (+T إن كسر تسلسل)",
    "methodology": "TIA/Windows",
    "description": "الرحاب المرحلة 8 (2023) – تعويض جزئي",
    "root_cause": "Not independently verified; review the original cited material and project facts.",
    "schedule_impact": "Fragnet cue as recorded: FR-065_A Omission Instruction → FR-065_B Re-assign to Others → FR-065_C Re-sequence Remaining",
    "recommended_solution": "Use this as an intake cue only; define the event, affected activities and links against the actual update before analysis.",
    "mitigation": "Not provided in the supplied intake.",
    "contractual_basis": "Source reference / مرجع المصدر: 12.4 / 13.7\n\nLegal locator as recorded / مؤشر قانوني كما ورد: مدني 147\n\nSource locator as recorded / مؤشر المصدر كما ورد: ف1/ح19",
    "fragnet_id": "FR-065_A Omission Instruction → FR-065_B Re-assign to Others → FR-065_C Re-sequence Remaining",
    "wbs_code": "",
    "fragnet_activities": "",
    "fragnet_protocol": "FR-065_A Omission Instruction → FR-065_B Re-assign to Others → FR-065_C Re-sequence Remaining",
    "tia_baseline_rule": "Verify the applicable baseline/update and data date against the project record.",
    "calendar_rule": "Verify the project calendar before calculating any impact.",
    "float_rule": "Verify total-float treatment against the contract and accepted programme.",
    "burden_of_proof": "Evidence requirements were not listed in the supplied intake.",
    "update_procedure": "F3 'Omission of Works – Re-assign'\n\nDuration=الإلغاء\n\nSS بالباقي\n\nF9",
    "recovery_procedure": "Not provided in the supplied intake."
  },
  {
    "id": "D-066",
    "case_id": "D-066",
    "title_ar": "تأخر الاستلام المؤقت للأعمال",
    "title_en": "Delayed Provisional Taking-Over",
    "category": "Inspection & Commissioning",
    "delay_type": "T + M",
    "methodology": "Milestone FF",
    "description": "مشاريع خليجية – 30 يوم EOT",
    "root_cause": "Not independently verified; review the original cited material and project facts.",
    "schedule_impact": "Fragnet cue as recorded: MIL 'Delayed Provisional Taking Over' ربط FF بالتسليم",
    "recommended_solution": "Use this as an intake cue only; define the event, affected activities and links against the actual update before analysis.",
    "mitigation": "Not provided in the supplied intake.",
    "contractual_basis": "Source reference / مرجع المصدر: 10.1\n\nLegal locator as recorded / مؤشر قانوني كما ورد: مدني 654، 656\n\nSource locator as recorded / مؤشر المصدر كما ورد: ف1/ح20",
    "fragnet_id": "MIL 'Delayed Provisional Taking Over' ربط FF بالتسليم",
    "wbs_code": "",
    "fragnet_activities": "",
    "fragnet_protocol": "MIL 'Delayed Provisional Taking Over' ربط FF بالتسليم",
    "tia_baseline_rule": "Verify the applicable baseline/update and data date against the project record.",
    "calendar_rule": "Verify the project calendar before calculating any impact.",
    "float_rule": "Verify total-float treatment against the contract and accepted programme.",
    "burden_of_proof": "Evidence requirements were not listed in the supplied intake.",
    "update_procedure": "Milestone 'Delayed Provisional Taking Over'\n\nربط FF بميلستون التسليم\n\nF9",
    "recovery_procedure": "Not provided in the supplied intake."
  },
  {
    "id": "D-067",
    "case_id": "D-067",
    "title_ar": "زيادة الكميات أكثر من 15–25%",
    "title_en": "Quantity Increase >15%",
    "category": "Design Changes & VO",
    "delay_type": "T + C",
    "methodology": "TIA",
    "description": "سكني 6 أكتوبر (2023) – EOT + تعويض",
    "root_cause": "Not independently verified; review the original cited material and project facts.",
    "schedule_impact": "Fragnet cue as recorded: FR-067_A Quantity Surge → FR-067_B Additional Procurement → FR-067_C Execute Extra Qty",
    "recommended_solution": "Use this as an intake cue only; define the event, affected activities and links against the actual update before analysis.",
    "mitigation": "Not provided in the supplied intake.",
    "contractual_basis": "Source reference / مرجع المصدر: 13.7 / 12.3\n\nLegal locator as recorded / مؤشر قانوني كما ورد: مدني 147 + م87/182-2018\n\nSource locator as recorded / مؤشر المصدر كما ورد: ف2/ح22",
    "fragnet_id": "FR-067_A Quantity Surge → FR-067_B Additional Procurement → FR-067_C Execute Extra Qty",
    "wbs_code": "",
    "fragnet_activities": "",
    "fragnet_protocol": "FR-067_A Quantity Surge → FR-067_B Additional Procurement → FR-067_C Execute Extra Qty",
    "tia_baseline_rule": "Verify the applicable baseline/update and data date against the project record.",
    "calendar_rule": "Verify the project calendar before calculating any impact.",
    "float_rule": "Verify total-float treatment against the contract and accepted programme.",
    "burden_of_proof": "Evidence requirements were not listed in the supplied intake.",
    "update_procedure": "F3 'Quantity Increase >15% – Concrete'\n\nDuration=الزيادة\n\nFS بالكميات\n\nF9",
    "recovery_procedure": "Not provided in the supplied intake."
  },
  {
    "id": "D-068",
    "case_id": "D-068",
    "title_ar": "تغيير طريقة التنفيذ (Precast→In-situ)",
    "title_en": "Construction Method Change",
    "category": "Design Changes & VO",
    "delay_type": "T + C",
    "methodology": "TIA",
    "description": "العاصمة الإدارية – 70 يوم",
    "root_cause": "Not independently verified; review the original cited material and project facts.",
    "schedule_impact": "Fragnet cue as recorded: FR-068_A Method VO → FR-068_B De-mobilize Old Method → FR-068_C New Method Works",
    "recommended_solution": "Use this as an intake cue only; define the event, affected activities and links against the actual update before analysis.",
    "mitigation": "Not provided in the supplied intake.",
    "contractual_basis": "Source reference / مرجع المصدر: 13.1\n\nLegal locator as recorded / مؤشر قانوني كما ورد: مدني 658\n\nSource locator as recorded / مؤشر المصدر كما ورد: ف2/ح24",
    "fragnet_id": "FR-068_A Method VO → FR-068_B De-mobilize Old Method → FR-068_C New Method Works",
    "wbs_code": "",
    "fragnet_activities": "",
    "fragnet_protocol": "FR-068_A Method VO → FR-068_B De-mobilize Old Method → FR-068_C New Method Works",
    "tia_baseline_rule": "Verify the applicable baseline/update and data date against the project record.",
    "calendar_rule": "Verify the project calendar before calculating any impact.",
    "float_rule": "Verify total-float treatment against the contract and accepted programme.",
    "burden_of_proof": "Evidence requirements were not listed in the supplied intake.",
    "update_procedure": "F3 'Method Change VO'\n\nDuration=التحويل\n\nFS بالجديد\n\nF9",
    "recovery_procedure": "Not provided in the supplied intake."
  },
  {
    "id": "D-069",
    "case_id": "D-069",
    "title_ar": "إصدار رسومات متضاربة أو بها أخطاء",
    "title_en": "Conflicting / Erroneous Drawings Issued",
    "category": "Owner/Consultant Delay",
    "delay_type": "T + C",
    "methodology": "TIA",
    "description": "مترو الخط الثالث (2019) – 55 يوم",
    "root_cause": "Not independently verified; review the original cited material and project facts.",
    "schedule_impact": "Fragnet cue as recorded: FR-069_A Conflict Identified → FR-069_B Correction Cycle → FR-069_C Execute to Corrected Dwg",
    "recommended_solution": "Use this as an intake cue only; define the event, affected activities and links against the actual update before analysis.",
    "mitigation": "Not provided in the supplied intake.",
    "contractual_basis": "Source reference / مرجع المصدر: 1.9 / 4.7\n\nLegal locator as recorded / مؤشر قانوني كما ورد: مدني 217\n\nSource locator as recorded / مؤشر المصدر كما ورد: ف2/ح25",
    "fragnet_id": "FR-069_A Conflict Identified → FR-069_B Correction Cycle → FR-069_C Execute to Corrected Dwg",
    "wbs_code": "",
    "fragnet_activities": "",
    "fragnet_protocol": "FR-069_A Conflict Identified → FR-069_B Correction Cycle → FR-069_C Execute to Corrected Dwg",
    "tia_baseline_rule": "Verify the applicable baseline/update and data date against the project record.",
    "calendar_rule": "Verify the project calendar before calculating any impact.",
    "float_rule": "Verify total-float treatment against the contract and accepted programme.",
    "burden_of_proof": "Evidence requirements were not listed in the supplied intake.",
    "update_procedure": "F3 'Conflicting Drawings Correction'\n\nDuration=التصحيح\n\nFS بالتنفيذ\n\nF9",
    "recovery_procedure": "Not provided in the supplied intake."
  },
  {
    "id": "D-070",
    "case_id": "D-070",
    "title_ar": "تغيير نوع الأساسات بعد البدء",
    "title_en": "Foundation Type Change After Start",
    "category": "Design Changes & VO",
    "delay_type": "T + C",
    "methodology": "TIA",
    "description": "16 عمارة 6 أكتوبر (حالة Amer) – 24 شهر",
    "root_cause": "Not independently verified; review the original cited material and project facts.",
    "schedule_impact": "Fragnet cue as recorded: FR-070_A Change Instruction → FR-070_B Redesign & Approve → FR-070_C New Excavation/Piles",
    "recommended_solution": "Use this as an intake cue only; define the event, affected activities and links against the actual update before analysis.",
    "mitigation": "Not provided in the supplied intake.",
    "contractual_basis": "Source reference / مرجع المصدر: 13.1 / 4.12\n\nLegal locator as recorded / مؤشر قانوني كما ورد: مدني 148، 658\n\nSource locator as recorded / مؤشر المصدر كما ورد: ف2/ح31",
    "fragnet_id": "FR-070_A Change Instruction → FR-070_B Redesign & Approve → FR-070_C New Excavation/Piles",
    "wbs_code": "",
    "fragnet_activities": "",
    "fragnet_protocol": "FR-070_A Change Instruction → FR-070_B Redesign & Approve → FR-070_C New Excavation/Piles",
    "tia_baseline_rule": "Verify the applicable baseline/update and data date against the project record.",
    "calendar_rule": "Verify the project calendar before calculating any impact.",
    "float_rule": "Verify total-float treatment against the contract and accepted programme.",
    "burden_of_proof": "Evidence requirements were not listed in the supplied intake.",
    "update_procedure": "F3 'Foundation Type Change'\n\nDuration=التعديل\n\nFS بالحفر الجديد\n\nF9",
    "recovery_procedure": "Not provided in the supplied intake."
  },
  {
    "id": "D-071",
    "case_id": "D-071",
    "title_ar": "Value Engineering من المالك بعد التوقيع",
    "title_en": "Owner Value Engineering Post-Contract",
    "category": "Design Changes & VO",
    "delay_type": "M",
    "methodology": "Cost فقط (تحديث Cash Flow)",
    "description": "مشاريع خليجية – تعويض جزئي",
    "root_cause": "Not independently verified; review the original cited material and project facts.",
    "schedule_impact": "Fragnet cue as recorded: N/A",
    "recommended_solution": "Use this as an intake cue only; define the event, affected activities and links against the actual update before analysis.",
    "mitigation": "Not provided in the supplied intake.",
    "contractual_basis": "Source reference / مرجع المصدر: 13.2\n\nLegal locator as recorded / مؤشر قانوني كما ورد: قانون التعاقدات + مدني 147\n\nSource locator as recorded / مؤشر المصدر كما ورد: ف2/ح32",
    "fragnet_id": "N/A",
    "wbs_code": "",
    "fragnet_activities": "",
    "fragnet_protocol": "N/A",
    "tia_baseline_rule": "Verify the applicable baseline/update and data date against the project record.",
    "calendar_rule": "Verify the project calendar before calculating any impact.",
    "float_rule": "Verify total-float treatment against the contract and accepted programme.",
    "burden_of_proof": "Evidence requirements were not listed in the supplied intake.",
    "update_procedure": "تحديث Cash Flow فقط\n\nلا Fragnet",
    "recovery_procedure": "Not provided in the supplied intake."
  },
  {
    "id": "D-072",
    "case_id": "D-072",
    "title_ar": "إضرابات عمالية عامة",
    "title_en": "General Labor Strikes",
    "category": "External / Neutral Events",
    "delay_type": "T",
    "methodology": "Windows",
    "description": "إضرابات 2022 – 30 يوم",
    "root_cause": "Not independently verified; review the original cited material and project facts.",
    "schedule_impact": "Fragnet cue as recorded: FR-072_A Strike Event → FR-072_B Stand-down → FR-072_C Resume",
    "recommended_solution": "Use this as an intake cue only; define the event, affected activities and links against the actual update before analysis.",
    "mitigation": "Not provided in the supplied intake.",
    "contractual_basis": "Source reference / مرجع المصدر: 8.4(d)/(e)\n\nLegal locator as recorded / مؤشر قانوني كما ورد: مدني 165\n\nSource locator as recorded / مؤشر المصدر كما ورد: ف3/ح36",
    "fragnet_id": "FR-072_A Strike Event → FR-072_B Stand-down → FR-072_C Resume",
    "wbs_code": "",
    "fragnet_activities": "",
    "fragnet_protocol": "FR-072_A Strike Event → FR-072_B Stand-down → FR-072_C Resume",
    "tia_baseline_rule": "Verify the applicable baseline/update and data date against the project record.",
    "calendar_rule": "Verify the project calendar before calculating any impact.",
    "float_rule": "Verify total-float treatment against the contract and accepted programme.",
    "burden_of_proof": "Evidence requirements were not listed in the supplied intake.",
    "update_procedure": "F3 'General Labor Strike – Month XX'\n\nDuration\n\nFS بالعمالة\n\nF9",
    "recovery_procedure": "Not provided in the supplied intake."
  },
  {
    "id": "D-073",
    "case_id": "D-073",
    "title_ar": "انقطاع الكهرباء العمومية الطويل",
    "title_en": "Prolonged Public Power Outage",
    "category": "External / Neutral Events (EG)",
    "delay_type": "T",
    "methodology": "Windows",
    "description": "انقطاعات 2023 – 25 يوم",
    "root_cause": "Not independently verified; review the original cited material and project facts.",
    "schedule_impact": "Fragnet cue as recorded: FR-073_A Outage → FR-073_B Idle Works → FR-073_C Resume",
    "recommended_solution": "Use this as an intake cue only; define the event, affected activities and links against the actual update before analysis.",
    "mitigation": "Not provided in the supplied intake.",
    "contractual_basis": "Source reference / مرجع المصدر: 8.4 + 4.19\n\nLegal locator as recorded / مؤشر قانوني كما ورد: مدني 165\n\nSource locator as recorded / مؤشر المصدر كما ورد: ف3/ح38",
    "fragnet_id": "FR-073_A Outage → FR-073_B Idle Works → FR-073_C Resume",
    "wbs_code": "",
    "fragnet_activities": "",
    "fragnet_protocol": "FR-073_A Outage → FR-073_B Idle Works → FR-073_C Resume",
    "tia_baseline_rule": "Verify the applicable baseline/update and data date against the project record.",
    "calendar_rule": "Verify the project calendar before calculating any impact.",
    "float_rule": "Verify total-float treatment against the contract and accepted programme.",
    "burden_of_proof": "Evidence requirements were not listed in the supplied intake.",
    "update_procedure": "F3 'Public Power Outage'\n\nDuration\n\nFS بالأعمال الكهربائية\n\nF9",
    "recovery_procedure": "Not provided in the supplied intake."
  },
  {
    "id": "D-074",
    "case_id": "D-074",
    "title_ar": "نقص المواد بالسوق (حديد/أسمنت/دولار)",
    "title_en": "Market Material Shortage",
    "category": "External (EG)",
    "delay_type": "T + C",
    "methodology": "Windows",
    "description": "أزمة 2022 مصر – EOT + ارتفاع أسعار",
    "root_cause": "Not independently verified; review the original cited material and project facts.",
    "schedule_impact": "Fragnet cue as recorded: FR-074_A Shortage Declared → FR-074_B Alternate Sourcing → FR-074_C Delivery",
    "recommended_solution": "Use this as an intake cue only; define the event, affected activities and links against the actual update before analysis.",
    "mitigation": "Not provided in the supplied intake.",
    "contractual_basis": "Source reference / مرجع المصدر: 8.4(d)\n\nLegal locator as recorded / مؤشر قانوني كما ورد: م87 قانون 182/2018\n\nSource locator as recorded / مؤشر المصدر كما ورد: ف3/ح39",
    "fragnet_id": "FR-074_A Shortage Declared → FR-074_B Alternate Sourcing → FR-074_C Delivery",
    "wbs_code": "",
    "fragnet_activities": "",
    "fragnet_protocol": "FR-074_A Shortage Declared → FR-074_B Alternate Sourcing → FR-074_C Delivery",
    "tia_baseline_rule": "Verify the applicable baseline/update and data date against the project record.",
    "calendar_rule": "Verify the project calendar before calculating any impact.",
    "float_rule": "Verify total-float treatment against the contract and accepted programme.",
    "burden_of_proof": "Evidence requirements were not listed in the supplied intake.",
    "update_procedure": "F3 'Material Shortage – Steel'\n\nDuration=النقص\n\nFS بالتوريد\n\nF9",
    "recovery_procedure": "Not provided in the supplied intake."
  },
  {
    "id": "D-075",
    "case_id": "D-075",
    "title_ar": "ارتفاع الأسعار الجنوني",
    "title_en": "Exceptional Price Escalation",
    "category": "External (EG) — Cost Only",
    "delay_type": "C",
    "methodology": "صيغ تعاقدية/أدلة أسعار (بدون Fragnet)",
    "description": "ما بعد 2022 – تعويض 20-30% من العقود",
    "root_cause": "Not independently verified; review the original cited material and project facts.",
    "schedule_impact": "Fragnet cue as recorded: N/A",
    "recommended_solution": "Use this as an intake cue only; define the event, affected activities and links against the actual update before analysis.",
    "mitigation": "Not provided in the supplied intake.",
    "contractual_basis": "Source reference / مرجع المصدر: 13.8\n\nLegal locator as recorded / مؤشر قانوني كما ورد: م87/182-2018 + مدني 147\n\nSource locator as recorded / مؤشر المصدر كما ورد: ف3/ح40",
    "fragnet_id": "N/A",
    "wbs_code": "",
    "fragnet_activities": "",
    "fragnet_protocol": "N/A",
    "tia_baseline_rule": "Verify the applicable baseline/update and data date against the project record.",
    "calendar_rule": "Verify the project calendar before calculating any impact.",
    "float_rule": "Verify total-float treatment against the contract and accepted programme.",
    "burden_of_proof": "Evidence requirements were not listed in the supplied intake.",
    "update_procedure": "Cost Claim فقط — لا زمني\n\nتطبيق معادلة التعويض",
    "recovery_procedure": "Not provided in the supplied intake."
  },
  {
    "id": "D-076",
    "case_id": "D-076",
    "title_ar": "إغلاق موانئ أو حدود",
    "title_en": "Port / Border Closure",
    "category": "Force Majeure",
    "delay_type": "T",
    "methodology": "Windows",
    "description": "إغلاقات كورونا – 50 يوم",
    "root_cause": "Not independently verified; review the original cited material and project facts.",
    "schedule_impact": "Fragnet cue as recorded: FR-076_A Closure Decree → FR-076_B Cargo Diverted/Held → FR-076_C Release",
    "recommended_solution": "Use this as an intake cue only; define the event, affected activities and links against the actual update before analysis.",
    "mitigation": "Not provided in the supplied intake.",
    "contractual_basis": "Source reference / مرجع المصدر: 19.1 / 8.4(d)\n\nLegal locator as recorded / مؤشر قانوني كما ورد: مدني 165، 373\n\nSource locator as recorded / مؤشر المصدر كما ورد: ف3/ح41",
    "fragnet_id": "FR-076_A Closure Decree → FR-076_B Cargo Diverted/Held → FR-076_C Release",
    "wbs_code": "",
    "fragnet_activities": "",
    "fragnet_protocol": "FR-076_A Closure Decree → FR-076_B Cargo Diverted/Held → FR-076_C Release",
    "tia_baseline_rule": "Verify the applicable baseline/update and data date against the project record.",
    "calendar_rule": "Verify the project calendar before calculating any impact.",
    "float_rule": "Verify total-float treatment against the contract and accepted programme.",
    "burden_of_proof": "Evidence requirements were not listed in the supplied intake.",
    "update_procedure": "F3 'Port Closure Delay'\n\nDuration\n\nFS بالاستيراد\n\nF9",
    "recovery_procedure": "Not provided in the supplied intake."
  },
  {
    "id": "D-077",
    "case_id": "D-077",
    "title_ar": "إفلاس مقاول فرعي مرشّح",
    "title_en": "Nominated Subcontractor Bankruptcy",
    "category": "Supplier/Vendor Delays",
    "delay_type": "T + C",
    "methodology": "TIA",
    "description": "حالات 2023 – EOT 90 يوم",
    "root_cause": "Not independently verified; review the original cited material and project facts.",
    "schedule_impact": "Fragnet cue as recorded: FR-077_A Bankruptcy Notice → FR-077_B Re-tender → FR-077_C New Sub Mobilization",
    "recommended_solution": "Use this as an intake cue only; define the event, affected activities and links against the actual update before analysis.",
    "mitigation": "Not provided in the supplied intake.",
    "contractual_basis": "Source reference / مرجع المصدر: 5.2 / 15.2\n\nLegal locator as recorded / مؤشر قانوني كما ورد: مدني 215\n\nSource locator as recorded / مؤشر المصدر كما ورد: ف4/ح49",
    "fragnet_id": "FR-077_A Bankruptcy Notice → FR-077_B Re-tender → FR-077_C New Sub Mobilization",
    "wbs_code": "",
    "fragnet_activities": "",
    "fragnet_protocol": "FR-077_A Bankruptcy Notice → FR-077_B Re-tender → FR-077_C New Sub Mobilization",
    "tia_baseline_rule": "Verify the applicable baseline/update and data date against the project record.",
    "calendar_rule": "Verify the project calendar before calculating any impact.",
    "float_rule": "Verify total-float treatment against the contract and accepted programme.",
    "burden_of_proof": "Evidence requirements were not listed in the supplied intake.",
    "update_procedure": "F3 'Subcontractor Bankruptcy'\n\nDuration=البديل\n\nFS بالأعمال\n\nF9",
    "recovery_procedure": "Not provided in the supplied intake."
  },
  {
    "id": "D-078",
    "case_id": "D-078",
    "title_ar": "نقل العمالة والمعدات المتكرر بين المواقع",
    "title_en": "Frequent Crew/Equipment Relocation",
    "category": "Disruption (Cost Only)",
    "delay_type": "C",
    "methodology": "Measured Mile + سجل نقلات",
    "description": "نقل بين مواقع – +15% تكلفة",
    "root_cause": "Not independently verified; review the original cited material and project facts.",
    "schedule_impact": "Fragnet cue as recorded: N/A — تكاليف نقل موثقة",
    "recommended_solution": "Use this as an intake cue only; define the event, affected activities and links against the actual update before analysis.",
    "mitigation": "Not provided in the supplied intake.",
    "contractual_basis": "Source reference / مرجع المصدر: 13.3\n\nLegal locator as recorded / مؤشر قانوني كما ورد: مدني 215\n\nSource locator as recorded / مؤشر المصدر كما ورد: ف6/ح59",
    "fragnet_id": "N/A — تكاليف نقل موثقة",
    "wbs_code": "",
    "fragnet_activities": "",
    "fragnet_protocol": "N/A — تكاليف نقل موثقة",
    "tia_baseline_rule": "Verify the applicable baseline/update and data date against the project record.",
    "calendar_rule": "Verify the project calendar before calculating any impact.",
    "float_rule": "Verify total-float treatment against the contract and accepted programme.",
    "burden_of_proof": "Evidence requirements were not listed in the supplied intake.",
    "update_procedure": "أضف تكاليف النقل كـ Cost Items\n\nلا Fragnet زمني",
    "recovery_procedure": "Not provided in the supplied intake."
  },
  {
    "id": "D-079",
    "case_id": "D-079",
    "title_ar": "توقف وتشغيل متكرر (Start-Stop)",
    "title_en": "Start-Stop Cycles (Hammock)",
    "category": "Disruption (Cost Only)",
    "delay_type": "C",
    "methodology": "MM + Hammock للتوقفات",
    "description": "تغييرات متكررة – انخفاض 28% (MCAA)",
    "root_cause": "Not independently verified; review the original cited material and project facts.",
    "schedule_impact": "Fragnet cue as recorded: Hammock 'Start-Stop Windows' (توثيق فقط)",
    "recommended_solution": "Use this as an intake cue only; define the event, affected activities and links against the actual update before analysis.",
    "mitigation": "Not provided in the supplied intake.",
    "contractual_basis": "Source reference / مرجع المصدر: — (Disruption)\n\nLegal locator as recorded / مؤشر قانوني كما ورد: مدني 159\n\nSource locator as recorded / مؤشر المصدر كما ورد: ف6/ح60",
    "fragnet_id": "Hammock 'Start-Stop Windows' (توثيق فقط)",
    "wbs_code": "",
    "fragnet_activities": "",
    "fragnet_protocol": "Hammock 'Start-Stop Windows' (توثيق فقط)",
    "tia_baseline_rule": "Verify the applicable baseline/update and data date against the project record.",
    "calendar_rule": "Verify the project calendar before calculating any impact.",
    "float_rule": "Verify total-float treatment against the contract and accepted programme.",
    "burden_of_proof": "Evidence requirements were not listed in the supplied intake.",
    "update_procedure": "Hammock للتوقفات\n\nExport إنتاجية Excel → MM → Import",
    "recovery_procedure": "Not provided in the supplied intake."
  },
  {
    "id": "D-080",
    "case_id": "D-080",
    "title_ar": "نقص المساحات التخزينية بالموقع",
    "title_en": "Insufficient Storage / Site Congestion",
    "category": "Disruption",
    "delay_type": "C (+T إن أثّر CP)",
    "methodology": "MM",
    "description": "مواقع ضيقة – Disruption 10%",
    "root_cause": "Not independently verified; review the original cited material and project facts.",
    "schedule_impact": "Fragnet cue as recorded: FR-080_A Storage Delay → FR-080_B Off-site Handling → FR-080_C Re-delivery",
    "recommended_solution": "Use this as an intake cue only; define the event, affected activities and links against the actual update before analysis.",
    "mitigation": "Not provided in the supplied intake.",
    "contractual_basis": "Source reference / مرجع المصدر: 4.19 / 2.1\n\nLegal locator as recorded / مؤشر قانوني كما ورد: مدني 148\n\nSource locator as recorded / مؤشر المصدر كما ورد: ف6/ح62",
    "fragnet_id": "FR-080_A Storage Delay → FR-080_B Off-site Handling → FR-080_C Re-delivery",
    "wbs_code": "",
    "fragnet_activities": "",
    "fragnet_protocol": "FR-080_A Storage Delay → FR-080_B Off-site Handling → FR-080_C Re-delivery",
    "tia_baseline_rule": "Verify the applicable baseline/update and data date against the project record.",
    "calendar_rule": "Verify the project calendar before calculating any impact.",
    "float_rule": "Verify total-float treatment against the contract and accepted programme.",
    "burden_of_proof": "Evidence requirements were not listed in the supplied intake.",
    "update_procedure": "Delay في التخزين\n\nF9 إن ربط بالـ CP",
    "recovery_procedure": "Not provided in the supplied intake."
  },
  {
    "id": "D-081",
    "case_id": "D-081",
    "title_ar": "تأخر صرف المستخلصات بسبب لجان الفحص",
    "title_en": "Inspection Committees Delaying IPCs",
    "category": "Egyptian Specific",
    "delay_type": "C (+T إن توقف)",
    "methodology": "Windows/Cash Flow",
    "description": "هيئة الإسكان – 45 يوم",
    "root_cause": "Not independently verified; review the original cited material and project facts.",
    "schedule_impact": "Fragnet cue as recorded: FR-081_A IPC Submitted → FR-081_B Committee Review → FR-081_C Payment",
    "recommended_solution": "Use this as an intake cue only; define the event, affected activities and links against the actual update before analysis.",
    "mitigation": "Not provided in the supplied intake.",
    "contractual_basis": "Source reference / مرجع المصدر: 14.8\n\nLegal locator as recorded / مؤشر قانوني كما ورد: م87/182-2018\n\nSource locator as recorded / مؤشر المصدر كما ورد: ف7/ح63",
    "fragnet_id": "FR-081_A IPC Submitted → FR-081_B Committee Review → FR-081_C Payment",
    "wbs_code": "",
    "fragnet_activities": "",
    "fragnet_protocol": "FR-081_A IPC Submitted → FR-081_B Committee Review → FR-081_C Payment",
    "tia_baseline_rule": "Verify the applicable baseline/update and data date against the project record.",
    "calendar_rule": "Verify the project calendar before calculating any impact.",
    "float_rule": "Verify total-float treatment against the contract and accepted programme.",
    "burden_of_proof": "Evidence requirements were not listed in the supplied intake.",
    "update_procedure": "F3 'Inspection Committee Delay'\n\nDuration\n\nFS بالأنشطة بعد الدفع\n\nF9",
    "recovery_procedure": "Not provided in the supplied intake."
  },
  {
    "id": "D-082",
    "case_id": "D-082",
    "title_ar": "تأخر موافقة الحي/المحافظة",
    "title_en": "District / Governorate Approval Delay",
    "category": "Egyptian Specific",
    "delay_type": "T",
    "methodology": "TIA",
    "description": "موافقات الحي – 60 يوم",
    "root_cause": "Not independently verified; review the original cited material and project facts.",
    "schedule_impact": "Fragnet cue as recorded: FR-082_A Application → FR-082_B District Review → FR-082_C Approval",
    "recommended_solution": "Use this as an intake cue only; define the event, affected activities and links against the actual update before analysis.",
    "mitigation": "Not provided in the supplied intake.",
    "contractual_basis": "Source reference / مرجع المصدر: 8.5\n\nLegal locator as recorded / مؤشر قانوني كما ورد: مدني 165، 148\n\nSource locator as recorded / مؤشر المصدر كما ورد: ف7/ح64",
    "fragnet_id": "FR-082_A Application → FR-082_B District Review → FR-082_C Approval",
    "wbs_code": "",
    "fragnet_activities": "",
    "fragnet_protocol": "FR-082_A Application → FR-082_B District Review → FR-082_C Approval",
    "tia_baseline_rule": "Verify the applicable baseline/update and data date against the project record.",
    "calendar_rule": "Verify the project calendar before calculating any impact.",
    "float_rule": "Verify total-float treatment against the contract and accepted programme.",
    "burden_of_proof": "Evidence requirements were not listed in the supplied intake.",
    "update_procedure": "F3 نشاط بمدة التأخير\n\nFS بالنشاط المتأثر\n\nF9",
    "recovery_procedure": "Not provided in the supplied intake."
  },
  {
    "id": "D-083",
    "case_id": "D-083",
    "title_ar": "قرارات إزالة مفاجئة من المجتمعات العمرانية",
    "title_en": "Sudden Demolition Decrees (New Cities)",
    "category": "Egyptian Specific",
    "delay_type": "T + C",
    "methodology": "TIA/Windows",
    "description": "المجتمعات العمرانية – EOT 90 يوم",
    "root_cause": "Not independently verified; review the original cited material and project facts.",
    "schedule_impact": "Fragnet cue as recorded: FR-083_A Decree → FR-083_B Demolition → FR-083_C Rebuild/Re-sequence",
    "recommended_solution": "Use this as an intake cue only; define the event, affected activities and links against the actual update before analysis.",
    "mitigation": "Not provided in the supplied intake.",
    "contractual_basis": "Source reference / مرجع المصدر: 13.7 / 17.4\n\nLegal locator as recorded / مؤشر قانوني كما ورد: مدني 651\n\nSource locator as recorded / مؤشر المصدر كما ورد: ف7/ح65",
    "fragnet_id": "FR-083_A Decree → FR-083_B Demolition → FR-083_C Rebuild/Re-sequence",
    "wbs_code": "",
    "fragnet_activities": "",
    "fragnet_protocol": "FR-083_A Decree → FR-083_B Demolition → FR-083_C Rebuild/Re-sequence",
    "tia_baseline_rule": "Verify the applicable baseline/update and data date against the project record.",
    "calendar_rule": "Verify the project calendar before calculating any impact.",
    "float_rule": "Verify total-float treatment against the contract and accepted programme.",
    "burden_of_proof": "Evidence requirements were not listed in the supplied intake.",
    "update_procedure": "نشاط إزالة\n\nFS\n\nF9",
    "recovery_procedure": "Not provided in the supplied intake."
  },
  {
    "id": "D-084",
    "case_id": "D-084",
    "title_ar": "تأخير لجان التقييم والتسعير الجديدة",
    "title_en": "New Pricing/Valuation Committees Delay",
    "category": "Egyptian Specific",
    "delay_type": "C",
    "methodology": "Cost",
    "description": "لجان 2024 – 50 يوم",
    "root_cause": "Not independently verified; review the original cited material and project facts.",
    "schedule_impact": "Fragnet cue as recorded: N/A",
    "recommended_solution": "Use this as an intake cue only; define the event, affected activities and links against the actual update before analysis.",
    "mitigation": "Not provided in the supplied intake.",
    "contractual_basis": "Source reference / مرجع المصدر: 13.8 / 12.3\n\nLegal locator as recorded / مؤشر قانوني كما ورد: قانون التعاقدات\n\nSource locator as recorded / مؤشر المصدر كما ورد: ف7/ح66",
    "fragnet_id": "N/A",
    "wbs_code": "",
    "fragnet_activities": "",
    "fragnet_protocol": "N/A",
    "tia_baseline_rule": "Verify the applicable baseline/update and data date against the project record.",
    "calendar_rule": "Verify the project calendar before calculating any impact.",
    "float_rule": "Verify total-float treatment against the contract and accepted programme.",
    "burden_of_proof": "Evidence requirements were not listed in the supplied intake.",
    "update_procedure": "Delay في التسعير — Cost Claim",
    "recovery_procedure": "Not provided in the supplied intake."
  },
  {
    "id": "D-085",
    "case_id": "D-085",
    "title_ar": "تغيير سعر الصرف الرسمي",
    "title_en": "Official Exchange Rate Change",
    "category": "Egyptian Specific — Cost Only",
    "delay_type": "C",
    "methodology": "Cost Claim (فروق عملة موثقة)",
    "description": "أزمة الدولار – تعويض 30%",
    "root_cause": "Not independently verified; review the original cited material and project facts.",
    "schedule_impact": "Fragnet cue as recorded: N/A",
    "recommended_solution": "Use this as an intake cue only; define the event, affected activities and links against the actual update before analysis.",
    "mitigation": "Not provided in the supplied intake.",
    "contractual_basis": "Source reference / مرجع المصدر: 13.8\n\nLegal locator as recorded / مؤشر قانوني كما ورد: م87/182-2018\n\nSource locator as recorded / مؤشر المصدر كما ورد: ف7/ح67",
    "fragnet_id": "N/A",
    "wbs_code": "",
    "fragnet_activities": "",
    "fragnet_protocol": "N/A",
    "tia_baseline_rule": "Verify the applicable baseline/update and data date against the project record.",
    "calendar_rule": "Verify the project calendar before calculating any impact.",
    "float_rule": "Verify total-float treatment against the contract and accepted programme.",
    "burden_of_proof": "Evidence requirements were not listed in the supplied intake.",
    "update_procedure": "Cost Claim فقط",
    "recovery_procedure": "Not provided in the supplied intake."
  },
  {
    "id": "D-086",
    "case_id": "D-086",
    "title_ar": "مشاكل الضرائب/التأمينات الاجتماعية",
    "title_en": "Tax / Social Insurance Disputes",
    "category": "Egyptian Specific",
    "delay_type": "T + C (إن Suspension)",
    "methodology": "Windows",
    "description": "تأمينات 2023 – 20 يوم",
    "root_cause": "Not independently verified; review the original cited material and project facts.",
    "schedule_impact": "Fragnet cue as recorded: FR-086_A Authority Action → FR-086_B Suspension → FR-086_C Release",
    "recommended_solution": "Use this as an intake cue only; define the event, affected activities and links against the actual update before analysis.",
    "mitigation": "Not provided in the supplied intake.",
    "contractual_basis": "Source reference / مرجع المصدر: 13.7\n\nLegal locator as recorded / مؤشر قانوني كما ورد: قوانين عمالية/ضريبية\n\nSource locator as recorded / مؤشر المصدر كما ورد: ف7/ح68",
    "fragnet_id": "FR-086_A Authority Action → FR-086_B Suspension → FR-086_C Release",
    "wbs_code": "",
    "fragnet_activities": "",
    "fragnet_protocol": "FR-086_A Authority Action → FR-086_B Suspension → FR-086_C Release",
    "tia_baseline_rule": "Verify the applicable baseline/update and data date against the project record.",
    "calendar_rule": "Verify the project calendar before calculating any impact.",
    "float_rule": "Verify total-float treatment against the contract and accepted programme.",
    "burden_of_proof": "Evidence requirements were not listed in the supplied intake.",
    "update_procedure": "Suspension activity\n\nFS\n\nF9",
    "recovery_procedure": "Not provided in the supplied intake."
  },
  {
    "id": "D-087",
    "case_id": "D-087",
    "title_ar": "اكتشاف آثار/مقبرة أثناء الحفر",
    "title_en": "Archaeological Discovery During Excavation",
    "category": "Rare / Force Majeure-like",
    "delay_type": "T + C",
    "methodology": "TIA",
    "description": "حفر بالقاهرة – EOT 120 يوم",
    "root_cause": "Not independently verified; review the original cited material and project facts.",
    "schedule_impact": "Fragnet cue as recorded: FR-087_A Discovery → FR-087_B Stop & Notify → FR-087_C Authority Works → FR-087_D Resume",
    "recommended_solution": "Use this as an intake cue only; define the event, affected activities and links against the actual update before analysis.",
    "mitigation": "Not provided in the supplied intake.",
    "contractual_basis": "Source reference / مرجع المصدر: 4.24\n\nLegal locator as recorded / مؤشر قانوني كما ورد: مدني 970، 972\n\nSource locator as recorded / مؤشر المصدر كما ورد: ف8/ح69",
    "fragnet_id": "FR-087_A Discovery → FR-087_B Stop & Notify → FR-087_C Authority Works → FR-087_D Resume",
    "wbs_code": "",
    "fragnet_activities": "",
    "fragnet_protocol": "FR-087_A Discovery → FR-087_B Stop & Notify → FR-087_C Authority Works → FR-087_D Resume",
    "tia_baseline_rule": "Verify the applicable baseline/update and data date against the project record.",
    "calendar_rule": "Verify the project calendar before calculating any impact.",
    "float_rule": "Verify total-float treatment against the contract and accepted programme.",
    "burden_of_proof": "Evidence requirements were not listed in the supplied intake.",
    "update_procedure": "F3 'Archaeological Discovery'\n\nDuration=الإيقاف\n\nFS\n\nF9",
    "recovery_procedure": "Not provided in the supplied intake."
  },
  {
    "id": "D-088",
    "case_id": "D-088",
    "title_ar": "انهيار تربة/انزلاق أرضي غير متوقع",
    "title_en": "Unforeseen Soil Collapse / Landslide",
    "category": "Rare / Unforeseeable Conditions",
    "delay_type": "T + C",
    "methodology": "TIA",
    "description": "مشاريع ري – 80 يوم",
    "root_cause": "Not independently verified; review the original cited material and project facts.",
    "schedule_impact": "Fragnet cue as recorded: FR-088_A Collapse → FR-088_B Geo Investigation → FR-088_C Repair/Redesign → FR-088_D Resume",
    "recommended_solution": "Use this as an intake cue only; define the event, affected activities and links against the actual update before analysis.",
    "mitigation": "Not provided in the supplied intake.",
    "contractual_basis": "Source reference / مرجع المصدر: 4.12\n\nLegal locator as recorded / مؤشر قانوني كما ورد: مدني 148\n\nSource locator as recorded / مؤشر المصدر كما ورد: ف8/ح70",
    "fragnet_id": "FR-088_A Collapse → FR-088_B Geo Investigation → FR-088_C Repair/Redesign → FR-088_D Resume",
    "wbs_code": "",
    "fragnet_activities": "",
    "fragnet_protocol": "FR-088_A Collapse → FR-088_B Geo Investigation → FR-088_C Repair/Redesign → FR-088_D Resume",
    "tia_baseline_rule": "Verify the applicable baseline/update and data date against the project record.",
    "calendar_rule": "Verify the project calendar before calculating any impact.",
    "float_rule": "Verify total-float treatment against the contract and accepted programme.",
    "burden_of_proof": "Evidence requirements were not listed in the supplied intake.",
    "update_procedure": "F3 'Soil Collapse Event'\n\nDuration=الإصلاح\n\nFS\n\nF9",
    "recovery_procedure": "Not provided in the supplied intake."
  }
];
