import { z } from "zod";
import { protectedProcedure, router } from "./_core/trpc";
import { createClaimCandidate, createClaimDeadlineTracker, createClaimRisk, listClaimConsole, upsertContractProfile } from "./claimConsole";

const key = z.string().trim().min(1).max(128);
const optionalText = z.string().trim().max(12_000).optional().nullable();
const sourceStatus = z.enum(["sourced", "to_enrich", "review_required", "rejected"]);

export const claimConsoleRouter = router({
  list: protectedProcedure.input(z.object({ projectKey: key })).query(({ ctx, input }) => listClaimConsole(ctx.user.id, input.projectKey)),
  saveContractProfile: protectedProcedure.input(z.object({ projectKey: key, contractTitle: z.string().trim().max(255).optional().nullable(), contractForm: z.string().trim().max(255).optional().nullable(), contractEdition: z.string().trim().max(160).optional().nullable(), specialConditionsReference: z.string().trim().max(255).optional().nullable(), governingLaw: z.string().trim().max(255).optional().nullable(), claimClauseReference: z.string().trim().max(255).optional().nullable(), noticeTriggerDescription: optionalText, sourceReference: optionalText, sourceStatus, reviewNotes: optionalText })).mutation(({ ctx, input }) => upsertContractProfile(ctx.user.id, input)),
  createRisk: protectedProcedure.input(z.object({ projectKey: key, riskKey: key, title: z.string().trim().min(3).max(255), description: z.string().trim().min(5).max(12_000), identifiedDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().nullable(), ownerRole: z.string().trim().max(120).optional().nullable(), sourceReference: optionalText, sourceStatus, status: z.enum(["open", "monitoring", "escalated", "closed"]), linkedPlannerIssueId: z.number().int().positive().optional().nullable(), reviewNotes: optionalText })).mutation(({ ctx, input }) => createClaimRisk(ctx.user.id, input)),
  createCandidate: protectedProcedure.input(z.object({ projectKey: key, candidateKey: key, title: z.string().trim().min(3).max(255), riskId: z.number().int().positive().optional().nullable(), plannerIssueLogId: z.number().int().positive().optional().nullable(), claimChainId: z.number().int().positive().optional().nullable(), contractClauseReference: z.string().trim().max(255).optional().nullable(), basisSummary: z.string().trim().min(5).max(12_000), sourceReference: optionalText, sourceStatus, status: z.enum(["draft", "under_review", "ready_for_notice", "linked_to_claim", "closed"]), reviewNotes: optionalText })).mutation(({ ctx, input }) => createClaimCandidate(ctx.user.id, input)),
  createDeadline: protectedProcedure.input(z.object({ projectKey: key, claimCandidateId: z.number().int().positive(), deadlineKey: key, title: z.string().trim().min(3).max(255), deadlineKind: z.enum(["notice", "particulars", "substantiation", "other"]), calculationMode: z.enum(["manual_date", "calendar_days"]), referenceDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().nullable(), calendarDays: z.number().int().min(0).max(36_500).optional().nullable(), dueDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().nullable(), ruleDescription: z.string().trim().min(5).max(12_000), sourceReference: optionalText, sourceStatus, status: z.enum(["unconfigured", "tracking", "review_required", "completed", "superseded"]), reviewNotes: optionalText })).mutation(({ ctx, input }) => createClaimDeadlineTracker(ctx.user.id, input)),
});
