import React, { useEffect, useMemo, useRef, useState } from "react";
import { AlertTriangle, BookOpenCheck, CheckCircle2, ChevronLeft, ChevronRight, FileSpreadsheet, FileUp, FolderCheck, GitBranch, LoaderCircle, Network, ShieldCheck, SplitSquareVertical, Upload } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { useAppLanguage } from "@/contexts/LanguageContext";
import { buildActivitySplitFragnet, type DelayCause, type Fragnet, type Schedule } from "@/lib/cpm";
import { downloadIssueImportTemplate, parseIssueRegisterExcel, type ExcelIssueRow } from "@/lib/issue-excel";
import type { XerImportSummary } from "@/lib/xer";
import "./guided-analysis.css";

export type ScheduleStage = "baseline" | "pre-event-update" | "later-update";
export type ScheduleSnapshot = { id: string; stage: ScheduleStage; fileName: string; schedule: Schedule; summary?: XerImportSummary };
type Props = {
  schedule: Schedule; xerSummary: XerImportSummary | null; journeyPath: "issue" | "direct" | null; journeyStep: number; p6GateApproved: boolean; qualityGateApproved: boolean; isXerImporting?: boolean;
  baselineSnapshot: ScheduleSnapshot | null; updateSnapshots: ScheduleSnapshot[];
  onJourneyPathChange: (value: "issue" | "direct" | null) => void; onJourneyStepChange: (step: number) => void; onP6GateApprovedChange: (value: boolean) => void; onQualityGateApprovedChange: (value: boolean) => void;
  onScheduleUpload: (stage: ScheduleStage, file: File) => Promise<void>; onNavigate: (view: "schedule" | "quality" | "issues" | "event" | "analysis" | "learning") => void;
  onApplyIssueExcel: (rows: ExcelIssueRow[]) => void; initialMethod?: "TIA" | "Windows" | "Disruption" | "Quantity";
  onPrepareSplit: (input: { activityId: string; title: string; description: string; occurrenceDate: string; duration: number; cause: DelayCause }) => void;
};

const interfaceCopy = {
  ar: {
    steps: ["الموسوعة", "المنهج", "Baseline", "Updates", "Excel", "التقسيم", "الحساب"],
    workshop: "Workshop 8 · رحلة TIA", panelTitle: "حلّل الواقعة بالتسلسل الصحيح", panelDescription: "تعلم، اختر المنهج، وثّق نسخ البرنامج والواقعة، ثم راجع التقسيم قبل الحساب.", currentStep: "الخطوة الحالية",
    libraryTitle: "ابدأ من الموسوعة، لا من التخمين", libraryDescription: "ابحث عن الحالة أو الدرس، ثم عد إلى هذه الرحلة لتوثيقها. اختر المسار المناسب قبل تحميل ملفات المشروع.", openLibrary: "افتح الموسوعة والدروس", issuePath: "سجل القضايا أولاً", issuePathDescription: "لواقعات متعددة تحتاج أدلة ومراجعة قبل النمذجة.", directPath: "تحليل مباشر", directPathDescription: "لواقعة واحدة جاهزة مع تاريخها وبياناتها.",
    methodTitle: "اختر منهج التحليل ولماذا", methodDescription: "لا يغير هذا الاختيار الملف الأصلي؛ إنما يحدد الإطار التحليلي والمسار التعليمي.", tiaNote: "حدث يحتاج قياس الأثر على برنامج متقبل.", windowsNote: "واقعات متتابعة ضمن نوافذ زمنية.", disruptionNote: "تعطيل أو فقد إنتاجية لا يختزل في حدث واحد.", quantityNote: "تغير نطاق أو كمية يحتاج قياس أثره.", methodDisclosure: "المحرك المحلي ينفذ TIA ببرنامج CPM. المسارات الأخرى تبقى موثقة في الموسوعة والسجلات ولا تُعرض كحساب TIA تلقائي.",
    baselineTitle: "ارفع Baseline المعتمد", baselineDescription: "الملف للقراءة فقط. عند الحساب ستنشأ نسخ Pre-TIA وPost-TIA مستقلة ولن يتغير ملفك الأصلي.", baseline: "Baseline المعتمد", baselineFileDescription: "XER أو XML أو JSON من Primavera P6", activities: "الأنشطة", relationships: "العلاقات", assignments: "إسنادات موارد",
    updateTitle: "Update قبل الحدث وبوابة الجودة", updateDescription: "آخر Update قبل الواقعة هو لقطة Pre-TIA. قبل إدخال أي واقعة، راجع سلامة الجدول والتقويم وData Date هنا.", preEventUpdate: "آخر Update قبل الحدث (إلزامي)", preEventDescription: "اختر النسخة الأقرب قبل تاريخ الواقعة", laterUpdate: "تحديث لاحق (اختياري)", laterUpdateDescription: "يمكن حفظ أكثر من تحديث للمتابعة بعد الحدث", baselineCount: "Baseline", preTiaCount: "Pre-TIA", activity: "نشاط", laterUpdatesSaved: "تحديث لاحق محفوظ للقراءة والمقارنة.", p6Gate: "بوابة تحقق P6", p6GateDescription: "راجع التقويم وData Date وعدادات الأنشطة والعلاقات قبل اعتماد نسخة Pre-TIA.", p6Acknowledgement: "أقرّ بمراجعة بيانات P6 قبل التحليل.", qualityGate: "بوابة جودة الجدول قبل الواقعة", qualityGateDescription: "دي مش موافقة شكلية: راجع المقارنات والملاحظات، وافتح شاشة «فحص الجدول» لو أي رقم مش مفهوم.", openQuality: "افتح فحص الجدول", qualityAcknowledgement: "راجعت بوابة الجودة وقلت إن الجدول صالح كبداية للتحليل أو سجلت ملاحظاتي.", readActivities: "الأنشطة المقروءة", logicalRelationships: "العلاقات المنطقية", dataDate: "تاريخ البيانات", calendarAndHolidays: "التقويم والإجازات",
    issueTitle: "سجل الواقعة المنظم — Workshop 8", issueDescription: "نزّل القالب أو أدخل واقعة مباشرة. تتحقق المنصة محلياً من نشاطك وعلاقته المنطقية في البرنامج المستورد.", downloadExcel: "تنزيل قالب Excel", uploadExcel: "رفع Excel", affectedActivity: "النشاط المتأثر", chooseFromSchedule: "اختر من البرنامج", occurrenceDate: "تاريخ الواقعة", duration: "المدة (يوم عمل)", cause: "السبب / المسؤولية", employer: "صاحب العمل Employer", contractor: "المقاول Contractor", neutral: "محايد / عام", eventTitleAndDescription: "عنوان ووصف الحدث", addEvent: "أضف الواقعة للنموذج", rowsReadyPrefix: "جاهز للمراجعة:", rowsReadySuffix: "واقعة منظمة مطابقة للبرنامج الحالي.", defaultEventTitle: "حدث تأخير محل التحليل", defaultEventDescription: "تقسيم النشاط المتأثر وفق نموذج Workshop 8 قبل إدراج حدث TIA.", analyst: "محلل TIA", workshopDescription: "واقعة منظمة في Workshop 8.", workshopImpact: "يُراجع الأثر زمنياً بعد إدراج الحدث في نسخة Post-TIA.", workshopReference: "يلزم توثيق المراسلات والأدلة قبل إصدار المطالبة.",
    splitTitle: "راجع تقسيم النشاط: Pre / Event / Post", splitDescription: "المعاينة مبنية على محرك CPM وعلى نسخة Pre-TIA؛ تغيير تاريخ الواقعة يعيد حساب مدتي قبل/بعد الحدث.", eventDate: "تاريخ الحدث", eventDuration: "مدة الحدث", day: "يوم", splitNote: "يستبدل النشاط داخل Post-TIA فقط بثلاثة أنشطة مرتبطة FS بلا Lag. ملف Baseline محفوظ للقراءة.", readyTitle: "النسخة التحليلية جاهزة للحساب", readyDescription: "تمت مراجعة الملفات والواقعة والتقسيم. سينشئ المحرك نسختين مستقلتين Pre-TIA وPost-TIA، ثم يحسب أثر الزمن محلياً.", openCalculation: "افتح الحساب وإنشاء الحدث",
    previous: "السابق", next: "التالي", results: "عرض النتائج", beforeNext: "قبل ما تدوس التالي", nextStep: "الخطوة الجاية", readyToContinue: "جاهز تكمل", calculationGuidance: "افتح الحساب، راجع Fragnet، وبعدها شغّل التحليل من شاشة النتائج.", readyGuidance: "كل المطلوب في الخطوة دي متسجل. دوس التالي.",
    notRecorded: "غير مسجل", local: "محلي", source: "المصدر", replace: "استبدال", upload: "رفع", fileActivity: "نشاط", fileRelationship: "علاقة", fileDataDate: "Data Date", choosePathToast: "اختر مسار سجل القضايا أو التحليل المباشر.", choosePathDetail: "اختار: سجل القضايا لو عندك أكتر من واقعة، أو تحليل مباشر لو هتبدأ بواقعة واحدة.", baselineToast: "رفع Baseline إلزامي قبل بدء تحليل TIA.", baselineDetail: "ارفع ملف Baseline المعتمد الأول. البرنامج هيقرأه فقط ومش هيعدّل الملف الأصلي.", updateToast: "ارفع آخر Update قبل الحدث؛ فهو نسخة Pre-TIA اللازمة للقياس.", updateDetail: "ارفع آخر Update قبل الواقعة. ده هو ملف Pre-TIA اللي هنقيس منه الأثر.", p6Toast: "أقرّ بمراجعة تقويم P6 وData Date قبل متابعة التحليل.", p6Detail: "علّم مربع مراجعة تقويم P6 وData Date بعد ما تراجعهم في الملف المستورد.", qualityToast: "مرّر بوابة الجودة بعد مراجعة Baseline وUpdate قبل إدخال الواقعة.", qualityDetail: "راجع عدادات الجدول والتقويم وData Date، ثم أقرّ بأنك راجعت الملاحظات قبل إضافة الحدث.", rowToast: "أدخل واقعة واحدة أو ارفع Excel صحيحاً قبل النمذجة.", rowDetail: "أضف واقعة من النموذج تحت، أو ارفع Excel من قالب سجل القضايا.", excelWarnings: "تمت قراءة Excel مع", excelNeedsCorrection: "ملاحظة تحتاج تصحيحاً.", excelReviewed: "تمت مراجعة", excelAgainstSchedule: "واقعة مقابل البرنامج المستورد.", excelReadError: "تعذر قراءة ملف Excel.", directRequired: "أكمل النشاط والعنوان والتاريخ والمدة أولاً.", noRelationship: "النشاط المختار لا يملك علاقة منطقية. اختر نشاطاً مرتبطاً أو استخدم Excel لتحديد رابط Fragnet.", rowAdded: "أضيفت الواقعة المنظمة إلى سجل Workshop 8.", splitRequired: "اختر نشاطاً وأدخل عنواناً وتاريخاً ومدة صحيحة.", splitError: "تعذر إعداد معاينة التقسيم."
  },
  en: {
    steps: ["Library", "Method", "Baseline", "Updates", "Excel", "Split", "Calculate"],
    workshop: "Workshop 8 · TIA journey", panelTitle: "Analyse the event in the right sequence", panelDescription: "Learn, select the method, document programme versions and the event, then review the split before calculating.", currentStep: "Current step",
    libraryTitle: "Start with the library, not assumptions", libraryDescription: "Find the relevant case or lesson, then return to this journey to document it. Choose the right path before loading project files.", openLibrary: "Open the library and lessons", issuePath: "Issue register first", issuePathDescription: "For multiple events that need evidence and review before modelling.", directPath: "Direct analysis", directPathDescription: "For one ready event with its date and details.",
    methodTitle: "Select the analysis method and why", methodDescription: "This selection does not change the original file; it identifies the analytical framework and learning path.", tiaNote: "An event requiring impact measurement on an accepted programme.", windowsNote: "Sequential events within time windows.", disruptionNote: "Disruption or productivity loss that cannot be reduced to one event.", quantityNote: "A scope or quantity change requiring impact assessment.", methodDisclosure: "The local engine runs TIA with CPM. Other paths remain documented in the library and registers and are not presented as an automatic TIA calculation.",
    baselineTitle: "Upload the approved Baseline", baselineDescription: "The file is read-only. Calculation creates separate Pre-TIA and Post-TIA copies and does not change your original file.", baseline: "Approved Baseline", baselineFileDescription: "XER, XML, or JSON from Primavera P6", activities: "Activities", relationships: "Relationships", assignments: "Resource assignments",
    updateTitle: "Pre-event Update and quality gate", updateDescription: "The last Update before the event is the Pre-TIA snapshot. Review programme integrity, calendar, and Data Date before entering any event.", preEventUpdate: "Last Update before the event (required)", preEventDescription: "Choose the closest version before the event date", laterUpdate: "Later Update (optional)", laterUpdateDescription: "More than one later update can be kept for post-event review", baselineCount: "Baseline", preTiaCount: "Pre-TIA", activity: "activity", laterUpdatesSaved: "later Update(s) retained for reading and comparison.", p6Gate: "P6 verification gate", p6GateDescription: "Review the calendar, Data Date, and activity and relationship counts before accepting the Pre-TIA copy.", p6Acknowledgement: "I confirm that I reviewed the P6 data before analysis.", qualityGate: "Pre-event schedule quality gate", qualityGateDescription: "This is not a formality: review the comparisons and notes, and open Schedule Quality if any value is unclear.", openQuality: "Open Schedule Quality", qualityAcknowledgement: "I reviewed the quality gate and confirmed the schedule is suitable as a starting point, or recorded my notes.", readActivities: "Activities read", logicalRelationships: "Logical relationships", dataDate: "Data Date", calendarAndHolidays: "Calendar and holidays",
    issueTitle: "Structured event register — Workshop 8", issueDescription: "Download the template or enter an event directly. The app validates the activity and its logical relationship locally against the imported programme.", downloadExcel: "Download Excel template", uploadExcel: "Upload Excel", affectedActivity: "Affected activity", chooseFromSchedule: "Choose from programme", occurrenceDate: "Event date", duration: "Duration (working day)", cause: "Cause / responsibility", employer: "Employer", contractor: "Contractor", neutral: "Neutral / general", eventTitleAndDescription: "Event title and description", addEvent: "Add event to the form", rowsReadyPrefix: "Ready for review:", rowsReadySuffix: "structured event(s) aligned to the current programme.", defaultEventTitle: "Delay event under analysis", defaultEventDescription: "Split the affected activity using the Workshop 8 model before inserting the TIA event.", analyst: "TIA analyst", workshopDescription: "Structured event in Workshop 8.", workshopImpact: "Time impact is reviewed after inserting the event in the Post-TIA copy.", workshopReference: "Correspondence and evidence must be documented before issuing a claim.",
    splitTitle: "Review the activity split: Pre / Event / Post", splitDescription: "The preview uses the CPM engine and the Pre-TIA copy; changing the event date recalculates the before/after durations.", eventDate: "Event date", eventDuration: "Event duration", day: "day(s)", splitNote: "Only Post-TIA replaces the activity with three FS-linked activities with no lag. The Baseline remains read-only.", readyTitle: "The analysis copy is ready to calculate", readyDescription: "Files, event, and split have been reviewed. The engine creates independent Pre-TIA and Post-TIA copies, then calculates time impact locally.", openCalculation: "Open calculation and create event",
    previous: "Previous", next: "Next", results: "View results", beforeNext: "Before you select Next", nextStep: "Next step", readyToContinue: "Ready to continue", calculationGuidance: "Open calculation, review the Fragnet, then run the analysis from the results screen.", readyGuidance: "Everything required for this step is recorded. Select Next.",
    notRecorded: "Not recorded", local: "Local", source: "Source", replace: "Replace", upload: "Upload", fileActivity: "activity", fileRelationship: "relationship", fileDataDate: "Data Date", choosePathToast: "Select an issue-register or direct-analysis path.", choosePathDetail: "Choose Issue register for more than one event, or Direct analysis to start with a single event.", baselineToast: "An approved Baseline is required before starting TIA.", baselineDetail: "Upload the approved Baseline first. The app reads it only and does not edit the original file.", updateToast: "Upload the last Update before the event; it is the Pre-TIA copy required for measurement.", updateDetail: "Upload the last Update before the event. This is the Pre-TIA file used to measure impact.", p6Toast: "Confirm your review of the P6 calendar and Data Date before continuing.", p6Detail: "Tick the P6 calendar and Data Date review box after reviewing them in the imported file.", qualityToast: "Pass the quality gate after reviewing Baseline and Update before entering the event.", qualityDetail: "Review the programme counts, calendar, and Data Date, then confirm that you reviewed the notes before adding the event.", rowToast: "Enter one event or upload a valid Excel file before modelling.", rowDetail: "Add an event using the form below, or upload Excel from the issue-register template.", excelWarnings: "Excel was read with", excelNeedsCorrection: "warning(s) requiring correction.", excelReviewed: "Reviewed", excelAgainstSchedule: "event(s) against the imported programme.", excelReadError: "Unable to read the Excel file.", directRequired: "Complete the activity, title, date, and duration first.", noRelationship: "The selected activity has no logical relationship. Choose a linked activity or use Excel to identify the Fragnet link.", rowAdded: "The structured event was added to Workshop 8.", splitRequired: "Select an activity and enter a valid title, date, and duration.", splitError: "Unable to prepare the split preview."
  }
} as const;

const dataDate = (schedule: Schedule | null | undefined, missing: string) => schedule?.dataDate || missing;

function FileSlot({ title, description, snapshot, loading, onPick, copy }: { title: string; description: string; snapshot?: ScheduleSnapshot | null; loading: boolean; onPick: (file: File) => void; copy: typeof interfaceCopy.ar | typeof interfaceCopy.en }) {
  const inputRef = useRef<HTMLInputElement>(null);
  return <div className={`guided-file-slot ${snapshot ? "guided-file-slot--ready" : ""}`}><input ref={inputRef} className="sr-only" type="file" accept=".xer,.xml,.json" onChange={(event) => { const file = event.target.files?.[0]; if (file) onPick(file); event.currentTarget.value = ""; }} />
    <span className="guided-file-slot__icon"><FileUp size={21} /></span><div><strong>{title}</strong><p>{snapshot ? `${snapshot.fileName} · ${snapshot.schedule.activities.length} ${copy.fileActivity} · ${snapshot.schedule.relationships.length} ${copy.fileRelationship}` : description}</p>{snapshot && <small>{copy.fileDataDate}: {dataDate(snapshot.schedule, copy.notRecorded)} · {copy.source}: {snapshot.schedule.source ?? copy.local}</small>}</div>
    <Button type="button" size="sm" variant={snapshot ? "outline" : "default"} disabled={loading} onClick={() => inputRef.current?.click()}>{loading ? <LoaderCircle size={16} className="animate-spin" /> : <Upload size={16} />}{snapshot ? copy.replace : copy.upload}</Button>
  </div>;
}

export function GuidedAnalysisPanel({ schedule, xerSummary, journeyPath, journeyStep, p6GateApproved, qualityGateApproved, isXerImporting = false, baselineSnapshot, updateSnapshots, onJourneyPathChange, onJourneyStepChange, onP6GateApprovedChange, onQualityGateApprovedChange, onScheduleUpload, onNavigate, onApplyIssueExcel, onPrepareSplit, initialMethod = "TIA" }: Props) {
  const { language, direction } = useAppLanguage();
  const copy = interfaceCopy[language];
  const [method, setMethod] = useState(initialMethod);
  const [rows, setRows] = useState<ExcelIssueRow[]>([]);
  const [excelErrors, setExcelErrors] = useState<string[]>([]);
  const [readingExcel, setReadingExcel] = useState(false);
  const [activityId, setActivityId] = useState("");
  const [title, setTitle] = useState<string>(copy.defaultEventTitle);
  const [description, setDescription] = useState<string>(copy.defaultEventDescription);
  const [occurrenceDate, setOccurrenceDate] = useState(schedule.dataDate ?? schedule.startDate);
  const [duration, setDuration] = useState("1");
  const [cause, setCause] = useState<DelayCause>("employer");
  const excelRef = useRef<HTMLInputElement>(null);
  const preEventUpdate = updateSnapshots.find(item => item.stage === "pre-event-update") ?? null;
  const laterUpdates = updateSnapshots.filter(item => item.stage === "later-update");
  const target = schedule.activities.find(item => item.id === activityId);
  const p6Source = baselineSnapshot?.schedule.source === "xer" || baselineSnapshot?.schedule.source === "p6-xml";
  const qualityChecks = useMemo(() => [
    { label: copy.readActivities, value: schedule.activities.length, pass: schedule.activities.length > 0 },
    { label: copy.logicalRelationships, value: schedule.relationships.length, pass: schedule.relationships.length > 0 },
    { label: copy.dataDate, value: schedule.dataDate ?? copy.notRecorded, pass: Boolean(schedule.dataDate) },
    { label: copy.calendarAndHolidays, value: schedule.calendar?.name ?? copy.notRecorded, pass: Boolean(schedule.calendar?.workingWeekdays.length) },
  ], [copy, schedule]);
  useEffect(() => {
    setActivityId(current => schedule.activities.some(item => item.id === current) ? current : schedule.activities[0]?.id ?? "");
    setOccurrenceDate(schedule.dataDate ?? schedule.startDate);
    onP6GateApprovedChange(false);
    onQualityGateApprovedChange(false);
  }, [schedule.id]);

  const splitPreview = useMemo(() => {
    if (!target || !title.trim() || !occurrenceDate || !Number.isFinite(Number(duration)) || Number(duration) < 0) return { fragnet: null as Fragnet | null, error: copy.splitRequired };
    try { return { fragnet: buildActivitySplitFragnet(schedule, { id: "SPLIT-PREVIEW", title: title.trim(), description: description.trim(), cause, occurrenceDate, eventDuration: Number(duration), targetActivityId: target.id }), error: "" }; }
    catch (error) { return { fragnet: null as Fragnet | null, error: error instanceof Error ? error.message : copy.splitError }; }
  }, [copy.splitError, copy.splitRequired, schedule, target?.id, title, description, cause, occurrenceDate, duration]);

  const nextRequirement = useMemo(() => {
    if (journeyStep === 1 && !journeyPath) return { toast: copy.choosePathToast, detail: copy.choosePathDetail };
    if (journeyStep === 3 && !baselineSnapshot) return { toast: copy.baselineToast, detail: copy.baselineDetail };
    if (journeyStep === 4 && !preEventUpdate) return { toast: copy.updateToast, detail: copy.updateDetail };
    if (journeyStep === 4 && p6Source && !p6GateApproved) return { toast: copy.p6Toast, detail: copy.p6Detail };
    if (journeyStep === 4 && !qualityGateApproved) return { toast: copy.qualityToast, detail: copy.qualityDetail };
    if (journeyStep === 5 && !rows.length) return { toast: copy.rowToast, detail: copy.rowDetail };
    if (journeyStep === 6 && !splitPreview.fragnet) return { toast: splitPreview.error, detail: splitPreview.error };
    return null;
  }, [journeyStep, journeyPath, baselineSnapshot, preEventUpdate, p6Source, p6GateApproved, qualityGateApproved, rows.length, splitPreview, copy]);

  function next() { if (nextRequirement) return toast.error(nextRequirement.toast); onJourneyStepChange(Math.min(7, journeyStep + 1)); }
  async function readExcel(file: File) {
    setReadingExcel(true);
    try { const parsed = parseIssueRegisterExcel(await file.arrayBuffer(), schedule); setRows(parsed.rows); setExcelErrors(parsed.errors); if (parsed.errors.length) toast.error(`${copy.excelWarnings} ${parsed.errors.length} ${copy.excelNeedsCorrection}`); else { onApplyIssueExcel(parsed.rows); toast.success(`${copy.excelReviewed} ${parsed.rows.length} ${copy.excelAgainstSchedule}`); } }
    catch (error) { setRows([]); setExcelErrors([error instanceof Error ? error.message : copy.excelReadError]); }
    finally { setReadingExcel(false); }
  }
  function addDirectRow() {
    if (!target || !title.trim() || !occurrenceDate || !Number.isFinite(Number(duration)) || Number(duration) <= 0) return toast.error(copy.directRequired);
    const relation = schedule.relationships.find(item => item.predecessorId === target.id || item.successorId === target.id);
    if (!relation) return toast.error(copy.noRelationship);
    const excelCause = cause === "concurrent" ? "neutral" : cause;
    const row: ExcelIssueRow = { rowNumber: 0, issueNo: `TIA-${String(rows.length + 1).padStart(3, "0")}`, title: title.trim(), occurrenceDate, reportedBy: copy.analyst, responsibleParty: cause === "employer" ? "employer" : cause === "contractor" ? "contractor" : "undetermined", delayCause: excelCause, criticality: "potentially_critical", proposedDurationDays: Number(duration), replacedRelationshipId: relation.id, affectedActivityIds: [target.id], description: description.trim() || copy.workshopDescription, impactSummary: copy.workshopImpact, referenceNotes: copy.workshopReference };
    const nextRows = [...rows, row]; setRows(nextRows); setExcelErrors([]); onApplyIssueExcel(nextRows); toast.success(copy.rowAdded);
  }
  const ForwardIcon = language === "ar" ? ChevronLeft : ChevronRight;
  const BackIcon = language === "ar" ? ChevronRight : ChevronLeft;
  const methodNotes = { TIA: copy.tiaNote, Windows: copy.windowsNote, Disruption: copy.disruptionNote, Quantity: copy.quantityNote } as const;

  return <section className="guided-panel" dir={direction}>
    <header className="guided-panel__header"><div><Badge className="guided-panel__badge">{copy.workshop}</Badge><h2>{copy.panelTitle}</h2><p>{copy.panelDescription}</p></div><div className="guided-panel__status"><b>{journeyStep} / 7</b><small>{copy.currentStep}</small></div></header>
    <ol className="guided-stepper">{copy.steps.map((label, index) => <li key={label} className={journeyStep === index + 1 ? "is-active" : journeyStep > index + 1 ? "is-done" : ""}><span>{journeyStep > index + 1 ? <CheckCircle2 size={16} /> : index + 1}</span><em>{label}</em></li>)}</ol>
    {journeyStep === 1 && <div className="guided-content"><div className="guided-hero-card"><BookOpenCheck size={28} /><div><h3>{copy.libraryTitle}</h3><p>{copy.libraryDescription}</p><Button type="button" variant="outline" onClick={() => onNavigate("learning")}>{copy.openLibrary} <ForwardIcon size={16} /></Button></div></div><div className="guided-paths"><button type="button" className={journeyPath === "issue" ? "is-selected" : ""} onClick={() => onJourneyPathChange("issue")}><FileSpreadsheet size={24} /><strong>{copy.issuePath}</strong><span>{copy.issuePathDescription}</span></button><button type="button" className={journeyPath === "direct" ? "is-selected" : ""} onClick={() => onJourneyPathChange("direct")}><Network size={24} /><strong>{copy.directPath}</strong><span>{copy.directPathDescription}</span></button></div></div>}
    {journeyStep === 2 && <div className="guided-content"><div className="guided-section-heading"><GitBranch size={22} /><div><h3>{copy.methodTitle}</h3><p>{copy.methodDescription}</p></div></div><div className="guided-method-grid">{(["TIA", "Windows", "Disruption", "Quantity"] as const).map(id => <button type="button" key={id} className={method === id ? "is-selected" : ""} onClick={() => setMethod(id)}><strong>{id}</strong><small>{id === "Quantity" ? (language === "ar" ? "زيادة كميات" : "Quantity increase") : id === "Windows" ? "Window Analysis" : id === "Disruption" ? "Disruption Analysis" : "Time Impact Analysis"}</small><span>{methodNotes[id]}</span></button>)}</div><p className="guided-disclosure">{copy.methodDisclosure}</p></div>}
    {journeyStep === 3 && <div className="guided-content"><div className="guided-section-heading"><FolderCheck size={22} /><div><h3>{copy.baselineTitle}</h3><p>{copy.baselineDescription}</p></div></div><FileSlot title={copy.baseline} description={copy.baselineFileDescription} snapshot={baselineSnapshot} loading={isXerImporting} onPick={file => onScheduleUpload("baseline", file)} copy={copy} />{baselineSnapshot && <div className="guided-stat-grid"><div><b>{baselineSnapshot.schedule.activities.length}</b><small>{copy.activities}</small></div><div><b>{baselineSnapshot.schedule.relationships.length}</b><small>{copy.relationships}</small></div><div><b>{baselineSnapshot.schedule.wbsNodes?.length ?? baselineSnapshot.summary?.wbsRead ?? 0}</b><small>WBS</small></div><div><b>{baselineSnapshot.schedule.resourceAssignments?.length ?? baselineSnapshot.summary?.resourceAssignmentsRead ?? 0}</b><small>{copy.assignments}</small></div></div>}</div>}
    {journeyStep === 4 && <div className="guided-content"><div className="guided-section-heading"><GitBranch size={22} /><div><h3>{copy.updateTitle}</h3><p>{copy.updateDescription}</p></div></div><FileSlot title={copy.preEventUpdate} description={copy.preEventDescription} snapshot={preEventUpdate} loading={isXerImporting} onPick={file => onScheduleUpload("pre-event-update", file)} copy={copy} />{preEventUpdate && <div className="guided-compare-strip"><span>{copy.baselineCount}: {baselineSnapshot?.schedule.activities.length ?? 0} {copy.activity}</span><ForwardIcon size={15} /><span>{copy.preTiaCount}: {preEventUpdate.schedule.activities.length} {copy.activity}</span><Badge variant="outline">Data Date: {dataDate(preEventUpdate.schedule, copy.notRecorded)}</Badge></div>}<FileSlot title={copy.laterUpdate} description={copy.laterUpdateDescription} snapshot={laterUpdates.at(-1)} loading={isXerImporting} onPick={file => onScheduleUpload("later-update", file)} copy={copy} />{laterUpdates.length > 0 && <p className="guided-file-history">{laterUpdates.length} {copy.laterUpdatesSaved}</p>}{p6Source && <div className="guided-gate"><div><ShieldCheck size={21} /><strong>{copy.p6Gate}</strong><p>{copy.p6GateDescription}</p></div><label><input type="checkbox" checked={p6GateApproved} onChange={event => onP6GateApprovedChange(event.target.checked)} /> {copy.p6Acknowledgement}</label>{xerSummary?.warnings?.slice(0, 3).map(warning => <p key={warning}><AlertTriangle size={14} />{warning}</p>)}</div>}{preEventUpdate && <div className="guided-gate guided-gate--quality"><div><ShieldCheck size={21} /><strong>{copy.qualityGate}</strong><p>{copy.qualityGateDescription}</p></div><div className="guided-quality-checks">{qualityChecks.map(check => <span key={check.label} className={check.pass ? "is-pass" : "is-warning"}>{check.pass ? <CheckCircle2 size={14} /> : <AlertTriangle size={14} />}<b>{check.label}</b><small>{check.value}</small></span>)}</div><Button type="button" size="sm" variant="outline" onClick={() => onNavigate("quality")}>{copy.openQuality}</Button><label><input type="checkbox" checked={qualityGateApproved} onChange={event => onQualityGateApprovedChange(event.target.checked)} /> {copy.qualityAcknowledgement}</label></div>}</div>}
    {journeyStep === 5 && <div className="guided-content"><div className="guided-section-heading"><FileSpreadsheet size={22} /><div><h3>{copy.issueTitle}</h3><p>{copy.issueDescription}</p></div></div><div className="guided-excel-actions"><Button type="button" variant="outline" onClick={downloadIssueImportTemplate}><FileSpreadsheet size={16} />{copy.downloadExcel}</Button><input ref={excelRef} className="sr-only" type="file" accept=".xlsx,.xls" onChange={event => { const file = event.target.files?.[0]; if (file) readExcel(file); event.currentTarget.value = ""; }} /><Button type="button" onClick={() => excelRef.current?.click()} disabled={readingExcel}>{readingExcel ? <LoaderCircle className="animate-spin" size={16} /> : <Upload size={16} />}{copy.uploadExcel}</Button></div><div className="guided-direct-form"><div><Label>{copy.affectedActivity}</Label><Select value={activityId} onValueChange={setActivityId}><SelectTrigger><SelectValue placeholder={copy.chooseFromSchedule} /></SelectTrigger><SelectContent>{schedule.activities.map(activity => <SelectItem value={activity.id} key={activity.id}>{activity.id} — {activity.name}</SelectItem>)}</SelectContent></Select></div><div><Label>{copy.occurrenceDate}</Label><Input type="date" value={occurrenceDate} onChange={event => setOccurrenceDate(event.target.value)} /></div><div><Label>{copy.duration}</Label><Input type="number" min="0" value={duration} onChange={event => setDuration(event.target.value)} /></div><div><Label>{copy.cause}</Label><Select value={cause} onValueChange={value => setCause(value as DelayCause)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="employer">{copy.employer}</SelectItem><SelectItem value="contractor">{copy.contractor}</SelectItem><SelectItem value="neutral">{copy.neutral}</SelectItem></SelectContent></Select></div><div className="guided-direct-form__wide"><Label>{copy.eventTitleAndDescription}</Label><Input value={title} onChange={event => setTitle(event.target.value)} /><Textarea value={description} onChange={event => setDescription(event.target.value)} /></div><Button type="button" variant="outline" onClick={addDirectRow}>{copy.addEvent}</Button></div>{excelErrors.length > 0 && <div className="guided-errors">{excelErrors.map(error => <p key={error}><AlertTriangle size={15} />{error}</p>)}</div>}{rows.length > 0 && <div className="guided-row-summary"><CheckCircle2 size={18} />{copy.rowsReadyPrefix} {rows.length} {copy.rowsReadySuffix}</div>}</div>}
    {journeyStep === 6 && <div className="guided-content"><div className="guided-section-heading"><SplitSquareVertical size={22} /><div><h3>{copy.splitTitle}</h3><p>{copy.splitDescription}</p></div></div><div className="guided-split-controls"><div><Label>{copy.affectedActivity}</Label><Select value={activityId} onValueChange={setActivityId}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{schedule.activities.map(activity => <SelectItem key={activity.id} value={activity.id}>{activity.id} — {activity.name}</SelectItem>)}</SelectContent></Select></div><div><Label>{copy.eventDate}</Label><Input type="date" value={occurrenceDate} onChange={event => setOccurrenceDate(event.target.value)} /></div><div><Label>{copy.eventDuration}</Label><Input type="number" min="0" value={duration} onChange={event => setDuration(event.target.value)} /></div></div>{splitPreview.fragnet ? <><div className="guided-split-visual">{splitPreview.fragnet.activities.map((activity, index) => <div key={activity.id} className={`guided-split-segment guided-split-segment--${index}`}><small>{index === 0 ? "Pre" : index === 1 ? "Event" : "Post"}</small><b>{activity.duration} {copy.day}</b><span>{activity.name}</span></div>)}</div><p className="guided-split-note"><CheckCircle2 size={17} />{copy.splitNote}</p></> : <div className="guided-errors"><p><AlertTriangle size={15} />{splitPreview.error}</p></div>}</div>}
    {journeyStep === 7 && <div className="guided-content"><div className="guided-hero-card guided-hero-card--ready"><ShieldCheck size={28} /><div><h3>{copy.readyTitle}</h3><p>{copy.readyDescription}</p><Button type="button" onClick={() => { if (!splitPreview.fragnet) return toast.error(splitPreview.error); onPrepareSplit({ activityId, title, description, occurrenceDate, duration: Number(duration), cause }); onNavigate("event"); }}>{copy.openCalculation} <ForwardIcon size={16} /></Button></div></div></div>}
    <footer className="guided-footer"><Button type="button" variant="outline" disabled={journeyStep === 1} onClick={() => onJourneyStepChange(Math.max(1, journeyStep - 1))}><BackIcon size={16} />{copy.previous}</Button><div id="journey-next-hint" className={`guided-footer__guidance ${nextRequirement ? "is-blocked" : "is-ready"}`} role="status">{nextRequirement ? <AlertTriangle size={18} /> : <CheckCircle2 size={18} />}<div><strong>{nextRequirement ? copy.beforeNext : journeyStep === 7 ? copy.nextStep : copy.readyToContinue}</strong><span>{nextRequirement ? nextRequirement.detail : journeyStep === 7 ? copy.calculationGuidance : copy.readyGuidance}</span></div></div>{journeyStep < 7 ? <Button type="button" disabled={Boolean(nextRequirement)} aria-describedby="journey-next-hint" onClick={next}>{copy.next} <ForwardIcon size={16} /></Button> : <Button type="button" variant="outline" onClick={() => onNavigate("analysis")}>{copy.results}</Button>}</footer>
  </section>;
}
